language: "ruby"

rvm:
  - "2.4"
  - "2.5"
  - "2.6"
  - "jruby-9.1"

sudo: false

install:
  - bundle install --retry=3

matrix:
  include:
    - rvm: "2.6"
      gemfile: "gemfiles/Gemfile.multi_json.x"
    - rvm: "2.6"
      gemfile: "gemfiles/Gemfile.yajl-ruby.x"
